version: '2'
services:
  php:
    image: yiisoftware/yii2-php:8.2-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8005:80'
    environment:
      - DB_DATABASE=${MYSQL_DATABASE}
      - DB_HOST=${MYSQL_HOST}
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
    depends_on:
      - db
  db:
    image: mysql:8
    env_file: .env    
    ports:
      - 3306:3306
    volumes:
      - ./mysql-data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8006:8080